- README.md
- README_CN.md
- cmd/main.go
- plugin/repository.go
- sdk/manager.go
> Support for downloading official plug-ins

- go.mod
- go.sum
- internal/config/config.go
- internal/config/config.yaml
- internal/config/config_test.go
- internal/config/proxy.go
- internal/sdk/manager.go
> Support proxy configuration #4

- cmd/commands/search.go
- go.mod
- go.sum
> Prints the searched version according to the terminal height

- cmd/commands/env.go
use `Record.Export` to search env variables.
> use Record.Export instead LoadAllSdk

- README.md
- README_CN.md
- docs/guides/quick-start.md
- docs/zh-hans/guides/quick-start.md
Since many beginners are using Powershell on the Windows system for development, it would be beneficial to enhance the usage instructions for beginners in Powershell.
It's possible to elegantly accomplish tasks with a single command by modifying the source code or using scripts, but this could introduce new complexity.
> Improve README for Powershell

- internal/printer/select.go
> Fixed the bug of selecting version for searching

- README_CN.md
- cmd/commands/use.go
- docs/plugins/create/howto.md
- docs/zh-hans/plugins/create/howto.md
- internal/fixtures/preload.lua
- internal/manager.go
- internal/path.go
- internal/plugin.go
- internal/plugin_test.go
- internal/scope.go
- internal/sdk.go
- internal/testdata/plugins/java.lua
- template.lua
> feat: support PreUse hook

- cmd/commands/search.go
- internal/printer/select.go
The current functionality only supports searching within the current page and finding results by turning pages. This PR implements the capability to search across all versions.
> Support for searching in all versions

- docs/guides/quick-start.md
- docs/zh-hans/guides/quick-start.md
Adds a Windows powershell mount instruction description to the document
> Fix doc with ps

- internal/env/windows_env.go
> Handling directory separators in env path

- cmd/commands/search.go
- internal/printer/select.go
> Highlight installed version when searching

- internal/manager.go
> Using the `VFOX_HOME/tmp` directory

- README.md
- README_CN.md
- internal/shell/clink.go
- internal/shell/clink_vfox.lua
Support the clink terminal's automatic completion and vfox environment switching functions by writing Lua scripts
link: https://github.com/version-fox/vfox/issues/129
> feat(add clink support): add clink to support window cmd terminal

- internal/printer/select.go
close: https://github.com/version-fox/vfox/issues/147
> fix(vfox search): remove the panic of no search

- internal/shell/clink_vfox.lua
only `vfox add` requires all sdk, other commands only need to autocomplete the added sdk.
> perf(clink autocomplete): use added plug-ins for autocomplete

- cmd/commands/update.go
- docs/usage/all-commands.md
- docs/zh-hans/usage/all-commands.md
run `vfox update --all` or `vfox update -a` to update all installed plugins
> feat: support update all installed plugins

- cmd/commands/activate.go
- cmd/commands/add.go
- cmd/commands/available.go
- cmd/commands/base.go
- cmd/commands/current.go
- cmd/commands/env.go
- cmd/commands/info.go
- cmd/commands/install.go
- cmd/commands/list.go
- cmd/commands/remove.go
- cmd/commands/search.go
- cmd/commands/uninstall.go
- cmd/commands/update.go
- cmd/commands/use.go
> feat: optimize cli help messages

- docs/plugins/available.md
A (very) small fix.
Keep up the good work :)
> docs: Available Plugins typo fix

- internal/plugin.go
- internal/sdk.go
- internal/util/verison.go
> `vfox use` fuzzy match version number

- internal/sdk.go
> Fix version alias installation

- cmd/commands/config.go
show configuration includes value as empty string
fix: https://github.com/version-fox/vfox/issues/233
> fix(vfox config -l): show all configurations

- install.sh
fixed: https://github.com/version-fox/vfox/issues/237
> fix: Resolve issue with missing /usr/local/bin directory

- docs/plugins/create/howto.md
- docs/zh-hans/plugins/create/howto.md
- internal/sdk.go
Add description for https://github.com/version-fox/vfox/pull/248.
> docs: Advanced PreInstall

- cmd/commands/config.go
> fix: support for missing string type

- cmd/commands/upgrade.go
https://github.com/version-fox/vfox/issues/275
> fix: create tempDir if not exist

- cmd/commands/activate.go
- internal/path.go
fix: https://github.com/version-fox/vfox/issues/313
> fix(env): reuse temporary directories across days

- internal/manager.go
When developling plugin can be usefull to have
symbolic link of the developed plugin in the v-fox plugin folder.
This commit makes it possible
> fix: Adds support for symlink for plugins

- internal/sdk.go
> fix: priority accurate matching version

- .goreleaser.yaml
> chore: ensure completion works

- internal/manager.go
Fixed missing error handling when adding plugins to vfox
fix https://github.com/version-fox/vfox/issues/369
> fix(add): install plugin null pointer

- internal/shell/clink_vfox.lua
1. Cache `vfox available` list
2. Execute the `vfox activate clink` command in the coroutine
3. Execute the `vfox env -s clink` command in the coroutine
fix: https://github.com/version-fox/vfox/issues/383
> perf(clink): improve clink startup speed

- docs/plugins/create/howto.md
- docs/plugins/library/http.md
- docs/zh-hans/plugins/create/howto.md
- docs/zh-hans/plugins/library/http.md
- internal/module/http/http.go
- internal/module/http/http_test.go
- internal/module/json/json.go
- internal/module/json/json_test.go
revert: https://github.com/version-fox/vfox/pull/385
> ci: fix json testcase

- internal/shell/clink_vfox.lua
In clink v1.7.8, when coroutine.resume(vfox_task) is used to resume the coroutine, the internal command cannot be executed successfully.
fix: https://github.com/version-fox/vfox/issues/408
> fix(vfox clink): clink coroutine execution failed

- go.mod
- go.sum
- internal/shell/windows_process.go
This reverts commit f822f0fc330e3feba06495780a57911d5592d5ef.
> Revert "hotfix: wmic deprecated (#402)"

- internal/shell/windows_process.go
> fix: replace wmic command with sys/windows to get the executable path

- docs/guides/quick-start.md
- docs/zh-hans/guides/quick-start.md
* fix docs style for `clink&cmder` doc
* docs: add tips for clink&cmder integration #440
> Fix cmder doc style

- internal/env/flag.go
- internal/path.go
Add VFOX_* environment variables to change the location of cache/temp/plugin directory
> feat: add VFOX_* environment variables

- internal/shell/powershell.go
fix #448 by by dynamically managing PowerShell modules and reverting changes made from previous one.
- Resetting `$function:prompt = $originalPrompt` fixed the infinite loop.  
- `Unregister-Event` prevents continuously registering new exit listeners.
> Credit for the clever idea goes to [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/shell/scripts/omp.ps1#L413)
> fix: prevent double initialize on powershell

- docs/zh-hans/guides/quick-start.md
> docs: fix error in chinese docs
