version-fox/vfox

sdk/plugin.go
file 'plugin.go' line 318 instance a local-variable which named 'L':which is a Lua VM 's instance.It's not a particularly clear naming so I rename 'L' to 'luaVMInstance'.Intended to make people more accurate to know its role
=> rename local-variable 'L' to 'luaVMInstance'

cmd/commands/env.go
hello, I have added a flag to get the paths in JSON format.
use cases:
```sh
vfox_data=$(vfox env --json)
for path in $(echo "$vfox_data" | jq -r '.paths[]'); do
export PATH="$PATH:$path"
done
for sdk_name in $(echo "$vfox_data" | jq -r '.sdks | keys_unsorted[]'); do
for var_name in $(echo "$vfox_data" | jq -r ".sdks.$sdk_name | keys_unsorted[]"); do
export "$var_name"=$(echo "$vfox_data" | jq -r ".sdks.$sdk_name.\"$var_name\"")
done
done
```
=> add a json flag in `vfox env` subcommand

internal/sdk.go
don't defer `Record.Save()`, because in case the block is entered:
```go
if !env.IsHookEnv() {
return shell.GetProcess().Open(os.Getppid())
}
```
an early return is performed, and the function is not finished executing, therefore the defer is never called.
=> don't defer Record.Save

cmd/commands/activate.go, cmd/commands/env.go, docs/plugins/create/howto.md, docs/zh-hans/plugins/create/howto.md, internal/env/env.go, internal/env/macos_env.go, internal/env/windows_env.go, internal/manager.go, internal/plugin.go, internal/plugin_test.go, internal/sdk.go, internal/shell/bash.go, internal/shell/fish.go, internal/shell/powershell.go, internal/shell/shell.go, internal/shell/zsh.go, internal/testdata/plugins/java.lua, template.lua
When the plugin configures multiple PATHs, there is no need to care about the specific OS delimiter, be it ; or :, just pass multiple PATHs and vfox will configure and de-duplicate them in order.
like this:
https://github.com/version-fox/version-fox-plugins/blob/9c8547364977506e2fdbe1b9ab83dc9b44d95c30/python/python.lua#L189-L192
=> refactor: Refactor EnvKeys to make configuring multiple PATHs smoother

internal/shell/powershell.go
1. Fix powershell prompt has been replaced, just using the original prompt.
2. 获取到原prompt后，先尝试匹配是否是默认[prompt](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.4)，如果是则适用默认方式生成prompt，否则适用自定义方式。
3. 为什么没有直接使用原始prompt？
`"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
` 这里的`>`似乎会变化，如果直接返回原始prompt就出现不一致。
=> fix(powershell): fix powershell prompt

internal/util/decompressor.go
=> Fix zip archive decompression problem.

internal/shell/powershell.go
1. Fix powershell env encoding.
2. Reference https://stackoverflow.com/questions/61112217/how-to-put-envlc-all-c-utf-8-on-profile-file-of-powershell
fix #116
=> fix(powershell): fix powershell env encoding

internal/manager.go
"No need update" is not a fail. No need to return error.
=> refactor: "No need update" is not a fail.

cmd/commands/search.go, internal/printer/select.go
=> Fixed the bug where the `search` did not stop listening after being interrupted by Ctrl+C

.github/workflows/ci.yml, .gitignore, internal/module/file/file_test.go, internal/module/http/http_test.go, internal/printer/select_test.go
add code coverage and report.
need codecov app, it can help show the test coverage in every pr.
@aooohan  could you help approve the installation of the Codecov app on GitHub for our organization? Here's the link: https://github.com/apps/codecov/installations/select_target
=> ci: add coverage and codecov

cmd/commands/add.go, cmd/commands/available.go, internal/config/config.go, internal/config/config.yaml, internal/config/registry.go, internal/manager.go, internal/plugin.go, internal/registry.go
fix #125 
fix #119
1. Only support `.lua` or `.zip` file type plugin.
2. Compatible with old plugin update way, which means old plug-ins can still be upgraded smoothly.
=> Refactor: Fetch plugin from Registry &  Allowing the switching of registry addresses.

internal/interfaces.go, internal/plugin.go
PHP's compilation process is so complex that I wrote a shell script for it, which can be found and executed via `PluginDirPath`. 
Or is there another way to execute the shell script?
=> Add `PluginDirPath` for `LuaRuntime`

internal/util/set.go, internal/util/set_test.go
…ce causes an error
Closes https://github.com/version-fox/vfox/issues/186
=> fix(internal): set slice should return a copy

internal/util/decompressor.go
Verify and create the containing directory when extracting symlink files
fix #198
=> Fixed exception when directory is not found while extracting symlink files

cmd/cmd.go, cmd/commands/config.go, docs/guides/configuration.md, docs/usage/all-commands.md, docs/zh-hans/guides/configuration.md, docs/zh-hans/usage/all-commands.md, internal/config/config.go
Idea from #204, this PR provides an alternative implementation.
It is implemented through reflection, so that you don't have to add a new `config` subcommand after adding a new config item.
cc @cifaz
=> Add config command

internal/manager.go, internal/sdk.go
=> Fix about adding plugin with alias

install.sh
Wrapped install.sh in a main function, then at the end of the script call main passing down all script arguments to the main function (if any become required in the future).
Reason for this change is that you recommend piping curl output directly into bash in the instructions, this change prevents install.sh from executing anything unless the whole file is downloaded successfully.
=> fix: wrap install.sh in a main function

internal/sdk.go
```powershell
PS C:\Users\zhylmzr> vfox --version
vfox version 0.4.0
PS C:\Users\zhylmzr> vfox u golang
Please select a version of golang:
-> 1.22.2
golang@ is not installed
```
fix #225
=> fix prefix match error

cmd/cmd.go, cmd/commands/upgrade.go, cmd/commands/upgrade_unix.go, cmd/commands/upgrade_win.go, install.sh
I have implemented the Windows part based on @ankit-pn's work at #38 and resolved the conflicts, it is now able to work as expected, namely upgrade to the latest version 0.4.1.
=> Support self upgrade

internal/shell/clink_vfox.lua
1. use `setdelayinit` to delay initialization, start clink faster, and only initialize when the `vfox` command is entered
2. `vfox add` supports completing multiple `sdk names`, and the `sdk name` already on the command line will not be completed again
4. add `vfox update`,`vfox upgrade`,`vfox config`,`vfox cd` command parameters auto-completion
=> feat(clink autocomplete): added clink auto-completion parameters

internal/shell/clink_vfox.lua
link: https://en.wikipedia.org/wiki/List_of_programming_languages
If languages ​​like `Objective-C` , `C++` are added in the future, this bug will need to be fixed.
=> fix(clink prompt sdk name): matches any programming language

docs/guides/configuration.md, docs/plugins/create/howto.md, docs/usage/core-commands.md, docs/zh-hans/guides/configuration.md, docs/zh-hans/plugins/create/howto.md, docs/zh-hans/usage/core-commands.md, internal/cache/cache.go, internal/cache/cache_test.go, internal/config/cache.go, internal/config/cache_test.go, internal/config/config.go, internal/config/config.yaml, internal/config/config_test.go, internal/plugin.go, internal/plugin_test.go, internal/testdata/plugins/java_with_main/main.lua, internal/testdata/plugins/java_with_metadata/hooks/available.lua
- Wrap the Available hook in the plugin with a layer of cache so that the cache can be used regardless of `vfox` calls or calls within the plugin.
- Allows configurable cache duration, defaults to 12 hours.
see https://github.com/version-fox/vfox/issues/227#issuecomment-2074205042
=> perf: cache `Available` results to reduce network io

internal/sdk.go
I would have tried to create a plugin yesterday (https://github.com/anweber/vfox-mani). It was hard because vfox is not always chatty about error. For example, the symlink was not created, but the command `vfox use mani@0.25.0` was completed without error.
Apparently, the optional hook `pre_use.lua` is expected to return the current version. Only then will the current folder be created, for which a symlink is generated. The dependencies are not well documented, so I was only able to determine the cause of the error after debugging vfox.
This MR now always logs the error and also displays the file name used (`targetDir .. "/current"`). This MR, does not fix the problem, that the first `PATH` variable must always have a subfolder `current`. If there is no pre_use hook, this folder may not …
=> fix: return err if symlink is not created

cmd/commands/config.go, internal/config/config.go
=> refactor: `config unset` reset to default config

cmd/commands/upgrade.go
Support using proxy to download vfox has been updated
=> perf(vfox upgrade): upgrade vfox use http proxy

internal/manager.go
fix: https://github.com/version-fox/vfox/issues/280
Keep temporary directory soft links when starting the terminal
=> fix: do not clean the temporary directory of the current terminal

go.mod, go.sum, internal/manager.go
fix: https://github.com/version-fox/vfox/issues/283
A running terminal's temporary directory should never be deleted
=> fix: do not clean temporary files of the shell which is running.

.gitignore, cmd/commands/current.go, cmd/commands/list.go, cmd/commands/update.go, internal/manager.go, internal/plugin_test.go, internal/sdk.go
https://github.com/version-fox/vfox/issues/277
Is there any automated testing to ensure the correctness of my code? I couldn't find the relevant script
=> feat: sort all sdks

docs/plugins/library/json.md, docs/zh-hans/plugins/library/json.md
Related to #303
close: #303
Corrects the URL reference in the documentation for the JSON library.
- Updates the URL reference in `docs/plugins/library/json.md` to the correct `gopher-json` link, removing an unnecessary trailing slash.
- Fixes the incorrect URL in `docs/zh-hans/plugins/library/json.md`, ensuring it points to `gopher-json` instead of `goquery`, aligning with the correct source.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/version-fox/vfox/issues/303?shareId=107307de-aedc-4ac6-806f-d1ae438a52f9).
=> docs: fix incorrect URL reference in JSON library documentation

docs/guides/quick-start.md, docs/zh-hans/guides/quick-start.md
close: #309 
doc(powershell): add powershell prompts that scripts is disabled on this system
=> docs: add powershell prompts that scripts is disabled on this system

README.md, README_CN.md, docs/guides/quick-start.md, docs/zh-hans/guides/quick-start.md
Add a single-line command to update the PowerShell profile for easier usage.
=> docs: add a single-line command to update the PowerShell profile

internal/shell/zsh.go
尝试修复问题 #294
增加判断，如果父进程已经存在变量`__VFOX_PID`则不在执行初始化, 避免子进程创建冗余目录干扰共享的环境变量
=> fix: determine whether vfox has been initialized in the parent process

internal/plugin.go
SDK like gcc-arm-none-eabi are well known with their dashes.
This commits allow plugins to have name with dashes.
=> fix: Add hyphen to the allowed plugin names

internal/sdk.go
fix(sdk.go): refactor GetLocalSdkPackage to improve version handling and simplify directory processing logic
=> fix: errors caused by hyphen support after upgrading to v0.5.5

internal/util/decompressor.go
=> feat(decompressor): add Bzip2TarDecompressor for handling .tar.bz2 files

internal/module/json/json.go
Pass an object to lua for modification, and the resulting return value. After serialization the field type changed. 
if not fix, the jsonBytes whill be 
```
{"metadata":[],"spec":{"containers":[{"image":"centos:7","name":"centos","resources":[]}]},"status":[]}
```
- metadata
- status
- resources
=> fix: lua encode structural error

README.md, cmd/commands/env.go, docs/guides/quick-start.md, internal/env/macos_env.go, internal/env/windows_env.go, internal/shell/nushell.go, internal/shell/nushell_test.go, internal/shell/shell.go
Implements #207
Though this implementation includes everything that needs done according to my understanding, it still doesn't seem to be working completely. I'd appreciate some help in figuring out what I might be missing. I believe the environment variables that are passed in to `Export` are being set correctly in the `pre_prompt` hook, but I'm not getting the expected SDKs and versions when I try to run them.
Also, note that this implementation wasn't quite as straightforward as I'd hoped, because Nushell doesn't have `eval`-like functionality. See https://www.nushell.sh/book/how_nushell_code_gets_run.html for more details, and see my comments below that point out how this impacts the implementation.
=> feat: Add Nushell support

internal/manager.go, internal/shell/clink_vfox.lua
1. Modify the cache file to vfox_available.txt, the meaning is clearer
2. When multiple commands are executed simultaneously in a Lua coroutine, only the first command succeeds, and the subsequent commands block the coroutine, so the second command is run through the coroutine
3. Print the error information returned by newPathMeta to facilitate troubleshooting
=> fix(clink_vfox.lua): Lua coroutine executes

go.mod, go.sum, internal/shell/windows_process.go
WMIC is deprecated as of Windows 10, version 21H1; and as of the 21H1 semi-annual channel release of Windows Server. This utility is superseded by Windows PowerShell for WMI; see Chapter 7 - Working with WMI. This deprecation applies only to the WMIC utility. Windows Management Instrumentation (WMI) itself is not affected. Also see Windows 10 features we're no longer developing.
https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic
https://github.com/version-fox/vfox/issues/401
=> hotfix: wmic deprecated

cmd/commands/activate.go, cmd/commands/cd.go, cmd/commands/env.go, internal/manager.go, internal/sdk.go, internal/shell/nushell.go
@colececil
because here we change the nushell config, so you need to restart twice to make the latest config work, or you will see an error.
=> fix(nushell): cannot switch version

docs/guides/quick-start.md, docs/zh-hans/guides/quick-start.md
* docs: add tips for `clink&cmder` integration
* [BUG]: Error 「 panic: panic: Init path meta error create temp dir failed: mkdir C:\Users\xxxxx\.version-fox\temp\1743004800-5460: Cannot create a file when that file already exists.」 in cmder terminal after win11 startup #439
=> docs: add tips for `clink&cmder` integration

internal/shim/shim_windows.go
fix #444 by utilizing `@params` (Splatting) instead of `$params`. 
This change should ensure that arguments are passed to the underlying executables correctly.
Users might need to regenerate their shims by runing `vfox use -g` to reflect new change.
=> fix: forward parameters with splatting on powershell shims

go.mod, internal/manager.go
The issue here was that the global environment was being inserted at the beginning of the MultiToolVersions slice, which mistakenly gave it a higher precedence than everything else in the slice. It should have a lowever precedence than the working directory, so the code has been modified to place it after that in the slice.
Fixes #420
=> fix: .`tool-versions` not working Nushell

cmd/commands/current.go, cmd/commands/list.go, cmd/commands/update.go, internal/interfaces.go, internal/luai/decode.go, internal/luai/encode.go, internal/luai/example_test.go, internal/luai/vm.go, internal/manager.go, internal/package.go, internal/plugin.go, internal/plugin_test.go, internal/sdk.go, internal/testdata/plugins/java_with_main/main.lua, internal/testdata/plugins/java_with_metadata/metadata.lua
This change updates the struct tags from `luai` to `json` across multiple files to maintain consistency with JSON serialization standards. This improves interoperability and aligns with common practices in Go for handling JSON data.
Prepare for support js plugin
=> refactor: replace luai tags with json for consistency

README_CN.md, docs/guides/intro.md, docs/index.md, docs/zh-hans/guides/intro.md, docs/zh-hans/guides/quick-start.md, docs/zh-hans/index.md
This adds Nushell to the website's lists of supported shells, and it also adds Nushell information missing from the Chinese versions of the readme and website (addressing #441).
(I don't know Chinese, but the additions seemed pretty straightforward. Please correct me if anything looks wrong.)
=> docs: Add Nushell information missing from website & readme

go.mod, go.sum
seeing build failure as below when [building 0.6.7 release on homebrew side](https://github.com/Homebrew/homebrew-core/pull/223837)
```
link: duplicated definition of symbol dlopen, from github.com/ebitengine/purego and github.com/ebitengine/purego
```
relates to:
- https://github.com/ebitengine/purego/issues/313
=> build: bump purego to build against newer go

internal/manager.go
Check and return error from NewSdk instead of ignoring it to prevent potential nil pointer issues
close: https://github.com/version-fox/vfox/issues/520
=> fix(manager): handle error when creating new SDK instance

internal/base/interfaces.go, internal/config/legacy_version_file.go, internal/plugin/plugin.go
Add support for three version selection strategies when parsing legacy version files:
1. latest_installed: use the latest installed version
2. latest_available: use the latest available version
3. specified: use the version specified in the file (default)
=> feat(legacy): add strategy support for legacy version file parsing

cmd/commands/install.go, cmd/commands/search.go, docs/usage/core-commands.md, docs/zh-hans/usage/core-commands.md, internal/manager.go, internal/shell/clink_vfox.lua
```
> vfox install nodejs@24
[php] not added yet, confirm that you want to use [php]?
Please confirm [y/N]:
```
```
> vfox install --yes nodejs@24
[nodejs] not added yet, automatically proceeding with installation. 
Downloading vfox-nodejs-0.3.0.zip...
Validating C:\Users\tiany\.version-fox\plugin\vfox-nodejs-0.3.0.zip ...
Plugin info:
Name     -> nodejs
Version  -> 0.3.0
Homepage -> https://github.com/version-fox/vfox-nodejs
Desc     -> Node.js runtime environment.
Add nodejs plugin successfully!
Please use `vfox install nodejs@<version>` to install the version you need.
nodejs@24.5.0 is already installed
```
----
```
> vfox install --all
Install the following plugins and SDKs:
SDK:
nodejs@21.3.0
Do you want to install these plugins and SDKs? [Y/n]:
```
```
> vfox install --all --yes …
```
=> feat: add `vfox install --yes` option for quick installation

docs/guides/configuration.md, docs/plugins/create/howto.md, docs/zh-hans/guides/configuration.md, docs/zh-hans/plugins/create/howto.md, internal/config/config_test.go, internal/config/legacy_version_file.go
Add strategy configuration support for legacy version file parsing with three options: latest_installed, latest_available, and specified. Update documentation to reflect these changes and default enable state.
=> feat(config): enable legacy version file by default
